.travis.yml
pom.xml
validationprofileparser/pom.xml
validationprofileparser/src/main/java/org/verapdf/validation/profile/model/Fix.java
validationprofileparser/src/main/java/org/verapdf/validation/profile/model/FixError.java
validationprofileparser/src/main/java/org/verapdf/validation/profile/model/FixInfo.java
validationprofileparser/src/main/java/org/verapdf/validation/profile/model/Reference.java
validationprofileparser/src/main/java/org/verapdf/validation/profile/model/Rule.java
validationprofileparser/src/main/java/org/verapdf/validation/profile/model/RuleError.java
validationprofileparser/src/main/java/org/verapdf/validation/profile/model/ValidationProfile.java
validationprofileparser/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileParser.java
validationprofileparser/src/test/java/org/verapdf/validation/profile/parser/ValidationProfileParserTest.java
validationprofileparser/src/test/resources/test.xml
validationprofileparser/src/test/resources/test2.xml
validationprofileparser/src/test/resources/testCyrillic.xml

Maven project and travis settings - Timur.
Valdiation profile parser - Maxim.

Validation profile parser. Maven project.

---

.gitignore
pom.xml
validationlogic/pom.xml
validationlogic/src/main/java/org/verapdf/validation/logic/Validator.java
validationlogic/src/main/java/org/verapdf/validation/report/XMLValidationReport.java
validationlogic/src/main/java/org/verapdf/validation/report/model/Check.java
validationlogic/src/main/java/org/verapdf/validation/report/model/CheckError.java
validationlogic/src/main/java/org/verapdf/validation/report/model/CheckLocation.java
validationlogic/src/main/java/org/verapdf/validation/report/model/Details.java
validationlogic/src/main/java/org/verapdf/validation/report/model/Profile.java
validationlogic/src/main/java/org/verapdf/validation/report/model/Result.java
validationlogic/src/main/java/org/verapdf/validation/report/model/Rule.java
validationlogic/src/main/java/org/verapdf/validation/report/model/Summary.java
validationlogic/src/main/java/org/verapdf/validation/report/model/ValidationInfo.java
validationlogic/src/test/java/org/verapdf/validation/logic/TestCosDict.java
validationlogic/src/test/java/org/verapdf/validation/logic/TestCosInteger.java
validationlogic/src/test/java/org/verapdf/validation/logic/TestObject.java
validationlogic/src/test/java/org/verapdf/validation/logic/TestPDAnnot.java
validationlogic/src/test/java/org/verapdf/validation/logic/ValidationLogicTest.java
validationlogic/src/test/resources/test.xml

Validation model, validation logic and validation xml report writer.

Validationlogic

---

validationprofileparser/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileParser.java
validationprofileparser/src/test/resources/test.xml
validationprofileparser/src/test/resources/test2.xml

Changed imports path processing from program relative to profile relative

Validation profile parser, import path's fix.

---

validationlogic/src/main/java/org/verapdf/validation/logic/Validator.java

Fixed library to correctly evaluate arguments and boolean values without expression.

validation logic fixes.

---

RELEASENOTES.md

Initial version of release notes for 0.1.0

Release notes 0 1 0

---

modelimplementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosDocument.java

https://github.com/veraPDF/pdfbox/pull/6

Support of linearized pdf

---

modelimplementation/src/main/java/org/verapdf/model/ModelLoader.java
modelimplementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosDocument.java
modelimplementation/src/main/java/org/verapdf/model/tools/XMPChecker.java

https://github.com/veraPDF/pdfbox/pull/7

Add support of 6.1.5 Document Information dictionary

---

.travis.yml
README.md
gui/.gitignore

Added further JDKs to the Travis builds and improved the README build instructions.

Travis JDKs and README improvements.

---

core/src/test/java/org/verapdf/integration/VeraPDFTestSuite.java
core/src/test/java/org/verapdf/integration/tools/ResultReporter.java
core/src/test/resources/test-resources/test-config.properties
core/src/test/resources/test-resources/testset.json

Base for results reporting.

---

core/src/test/java/org/verapdf/integration/VeraPDFTestSuite.java
core/src/test/java/org/verapdf/integration/model/reporting/TestSetReport.java
core/src/test/java/org/verapdf/integration/tools/ResultReporter.java
core/src/test/resources/log4j.properties
core/src/test/resources/test-resources/testset.json
model-implementation/src/main/java/org/verapdf/model/ModelLoader.java
pom.xml

1) clone integration branch of profiles repo
2) fixed test set
3) fixed logger
4) added total and failed properties to TestSetReport
5) Fix for ModelLoader related to closed streams

Fixes for integration tests :

---

core/src/test/java/org/verapdf/integration/VeraPDFTestSuite.java
core/src/test/java/org/verapdf/integration/model/TestEntity.java
core/src/test/java/org/verapdf/integration/model/reporting/TestEntityReport.java
core/src/test/java/org/verapdf/integration/tools/ResultReporter.java
core/src/test/resources/test-resources/testset.json
model-implementation/src/main/java/org/verapdf/model/factory/operator/OperatorFactory.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/external/PBoxICCOutputProfile.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/base/PBOperator.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/generalgs/PBOp_M_miter_limit.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/generalgs/PBOp_d.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/generalgs/PBOp_i.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/generalgs/PBOp_w_line_width.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/inlineimage/PBOpInlineImage.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/pathconstruction/PBOpPathConstruction.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDOutputIntent.java

Extended operators, test set.

---

model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDFormField.java

Check null for additional action of form field

PT-202: bug fix

---

model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDDocument.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDFormField.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDObject.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDPage.java

Implementation of actions for pages and catalog

Add support of actions for pages and document

---

model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDExtGState.java

Check parameter for null value for PDExtGState

PT-204: bug fix

---

model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textshow/PBOpStringTextShow.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textshow/PBOpTextShow.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textshow/PBOp_DoubleQuote.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textshow/PBOp_Quote.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textshow/PBOp_TJ_Big.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textshow/PBOp_Tj.java

Chapter 6.1.6 contains file in which present hex string with odd number of symbols. This string is operand for Tj operator, thus for bug fix we needed implement this operator.

PT-201: implement text show operator for bug fix

---

gui/pom.xml

- removed ad-hoc download from Jenkins;
- download veraPDF-corpus master;
- download veraPDF-validation-profile integration; and
- download veraPDF-model integration from GitHub.

GUI zip packaging updated.

---

core/src/test/resources/test-resources/testset.json
gui/src/main/java/org/verapdf/gui/PartnersPanel.java
gui/src/main/java/org/verapdf/gui/tools/GUIConstants.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDContentStream.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDExtGState.java

Added link to font size.

---

model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosStream.java

Change way of type cast for getLength() method.
Replace return object of getFilters() method from empty string to null.

PT-210: bug fix

---

feature-report/src/main/java/org/verapdf/features/pb/objects/PBInfoDictFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBLowLvlInfoFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBPageFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/tools/PBCreateNodeHelper.java
feature-report/src/main/java/org/verapdf/features/tools/ErrorsHelper.java

Methods which can be used in different features object moved into separate class.

Features report static methods refactor.

---

feature-report/pom.xml
feature-report/src/main/java/org/verapdf/features/FeaturesReporter.java
feature-report/src/main/java/org/verapdf/features/pb/PBFeatureParser.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBAnnotationFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBDocSecurityFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBEmbeddedFileFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBInfoDictFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBLowLvlInfoFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBMetadataFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBOutlinesFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBOutputIntentsFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBPageFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/tools/PBCreateNodeHelper.java
feature-report/src/main/java/org/verapdf/features/tools/ErrorsHelper.java
feature-report/src/main/java/org/verapdf/features/tools/FeatureTreeNode.java

Tidied up sonar errors, reduced complexity and added logging.

Features reporting refactored

---

feature-report/src/main/java/org/verapdf/features/pb/objects/PBDocSecurityFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBEmbeddedFileFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBLowLvlInfoFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBMetadataFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/tools/PBCreateNodeHelper.java
feature-report/src/main/java/org/verapdf/features/tools/ErrorsHelper.java

- added error logging for exceptions;
- removed unnecessary else statements;
- made one lookup map immutable;
- added comments plus some Javadoc; and
- reorgnaised imports.

Features reporting refactored.

---

feature-report/pom.xml
gui/pom.xml
gui/src/main/java/org/verapdf/gui/AboutPanel.java
gui/src/main/java/org/verapdf/gui/CheckerPanel.java
gui/src/main/java/org/verapdf/gui/LogoPanel.java
gui/src/main/java/org/verapdf/gui/MiniLogoPanel.java
gui/src/main/java/org/verapdf/gui/PartnersPanel.java

- reorganised imports;
- added log4J logging;
- added IDs for serialisation;
- made logging consistent;
- improved Javadoc;
- added missing override annotations;
- made non serialisable members transient;
- used try with resource to ensure streams closed;
- enforced dependency managment; and
- added logger for GUI module.

Re-factored GUI module and fixed Sonar criticals.

---

gui/src/main/java/org/verapdf/gui/CheckerPanel.java

- made non-serialisables transient; and
- logged file overwrite case.

Sonar fixes for CheckerPanel.

---

core/src/main/java/org/verapdf/runner/ValidationRunner.java
core/src/test/java/org/verapdf/integration/tools/ResultReporter.java
gui/src/main/java/org/verapdf/gui/PDFValidationApplication.java
gui/src/main/java/org/verapdf/gui/ValidateWorker.java
model-implementation/src/main/java/org/verapdf/model/ModelLoader.java
model-implementation/src/main/java/org/verapdf/model/factory/operator/OperatorFactory.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosDocument.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosObject.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/external/PBoxICCProfile.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/shading/PBOp_sh.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDContentStream.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDDocument.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDGroup.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDMetadata.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDOutputIntent.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDPage.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/colors/PBoxPDDeviceN.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/colors/PBoxPDICCBased.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/colors/PBoxPDIndexed.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/colors/PBoxPDSeparation.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDXForm.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDXImage.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDXObject.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/pattern/PBoxPDShading.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/pattern/PBoxPDShadingPattern.java
model-implementation/src/main/java/org/verapdf/model/tools/XMPChecker.java
validation-profile-parser/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileSignatureChecker.java
validation-report/src/main/java/org/verapdf/report/XMLFeaturesReport.java
validation-report/src/main/java/org/verapdf/report/XMLReport.java

- declarations of LOGGER now consistent;
- always log exception details;
- some JavaDoc reformatting;
- boxing errors addressed; and
- some unnecessary elses removed.

Consistent use of log4j.

---

feature-report/src/main/java/org/verapdf/features/pb/objects/PBLowLvlInfoFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/pb/objects/PBOutlinesFeaturesObject.java
feature-report/src/main/java/org/verapdf/features/tools/ErrorsHelper.java
feature-report/src/main/java/org/verapdf/features/tools/FeatureTreeNode.java
gui/src/main/java/org/verapdf/gui/CheckerPanel.java
gui/src/main/java/org/verapdf/gui/PDFValidationApplication.java
gui/src/main/java/org/verapdf/gui/PartnersPanel.java
gui/src/main/java/org/verapdf/gui/ValidateWorker.java
gui/src/main/java/org/verapdf/gui/tools/GUIConstants.java
validation-profile-parser/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileParser.java
validation-report/src/main/java/org/verapdf/report/XMLReport.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/VeraPDFException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/featurereport/FeaturesTreeNodeException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationlogic/JavaScriptEvaluatingException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationlogic/MultiplyGlobalVariableNameException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationlogic/NullLinkException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationlogic/NullLinkNameException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationlogic/NullLinkedObjectException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationlogic/RullWithNullIDException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationprofileparser/IncorrectImportPathException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationprofileparser/MissedHashTagException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationprofileparser/NullProfileException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationprofileparser/WrongProfileEncodingException.java
verapdf-exceptions/src/main/java/org/verapdf/exceptions/validationprofileparser/WrongSignatureException.java

- made methods static;
- organised imports;
- reformatted lines;
- added serialisation ID where required;
- removed unnecessary parenthesis;
- enforced static member access;

Fixing Sonarqube, compiler warnings.

---

core/pom.xml
gui/pom.xml
model-implementation/pom.xml
validation-logic/pom.xml
validation-report/pom.xml

- removed declared but unused inter project dependencies.

Maven dependency clean up.

---

validation-profile-parser/pom.xml
validation-profile-parser/src/main/java/org/verapdf/validation/profile/model/Rule.java
validation-profile-parser/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileParser.java
validation-profile-parser/src/test/java/org/verapdf/validation/profile/model/RuleTests.java

- added hashCode and equals;
- test for null; and
- ensure fixes is an empty list.

Basic unit tests for Profile Rule class.

---

validation-logic/src/main/java/org/verapdf/validation/logic/Validator.java
validation-logic/src/main/java/org/verapdf/validation/report/model/Check.java
validation-profile-parser/src/main/java/org/verapdf/validation/profile/model/Reference.java
validation-profile-parser/src/main/java/org/verapdf/validation/profile/model/Rule.java
validation-profile-parser/src/main/java/org/verapdf/validation/profile/model/ValidationProfile.java
validation-profile-parser/src/test/java/org/verapdf/validation/profile/parser/ValidationProfileParserTest.java
validation-report/src/main/java/org/verapdf/report/XMLValidationReport.java

- used passed or failed logic to implement for now.

Removed the isHasError() method.

---

model-implementation/src/main/java/org/verapdf/model/factory/operator/OperatorParser.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/base/PBOperator.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textposition/PBOp_Tm.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textstate/PBOpTextState.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textstate/PBOp_Tc.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textstate/PBOp_Tf.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textstate/PBOp_Tl.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textstate/PBOp_Ts.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textstate/PBOp_Tw.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/type3font/PBOpType3Font.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/type3font/PBOp_d0.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/type3font/PBOp_d1.java
model-implementation/src/test/java/org/verapdf/model/factory/operator/OperatorParserTest.java

https://github.com/veraPDF/veraPDF-model/pull/60

Implementation of new operators

---

model-implementation/src/main/java/org/verapdf/model/factory/font/FontFactory.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDFont.java
model-implementation/src/main/java/org/verapdf/model/tools/XMPChecker.java

1) CIDFontType2 embedded font file.
2) Incorrect handling of special symbols in metadata.

Fixed problems :

---

gui/src/main/java/org/verapdf/gui/SettingsPanel.java
gui/src/main/java/org/verapdf/gui/tools/GUIConstants.java
model-implementation/src/main/java/org/verapdf/model/factory/font/FontFactory.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDFont.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDType0Font.java
model-implementation/src/main/java/org/verapdf/model/tools/XMPChecker.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/pd/font/PBoxPDType0CIDType2Test.java

Fixes for:
- settings panel;
- CIDFontType2 embedded font file;
- incorrect handling of special symbols in metadata; and
- problem with registry & ordering checks.

Combined release fixes.

---

feature-report/src/main/java/org/verapdf/features/tools/FeaturesCollection.java
model-implementation/src/main/java/org/verapdf/model/factory/operator/OperatorFactory.java
model-implementation/src/main/java/org/verapdf/model/factory/operator/OperatorParser.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDInlineImage.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDXImage.java

https://github.com/veraPDF/veraPDF-pdfbox/pull/34
Can failed because of pdfbox changes not applied

Inline Images color spaces support

---

feature-report/src/main/java/org/verapdf/features/pb/tools/PBCreateNodeHelper.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosDocument.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosName.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosStream.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosString.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosXRef.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/cos/PBCosDictTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/cos/PBCosDocumentTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/cos/PBCosNameTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/cos/PBCosStreamTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/cos/PBCosStringTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/cos/PBCosXRefTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/operator/generalgs/PBOp_riTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/operator/textstate/PBOp_TfTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/pd/font/PBoxPDTrueTypeFontTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/pd/font/PBoxPDType0CIDType0Test.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/pd/font/PBoxPDType0CIDType2Test.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/pd/font/PBoxPDType1FontTest.java

https://github.com/veraPDF/veraPDF-pdfbox/pull/39

New box impl

---

model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosDocument.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosFileSpecification.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/external/PBoxEmbeddedFile.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/external/PBoxICCProfile.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/external/PBoxJPEG2000.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/external/PBoxTrueTypeFontProgram.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/operator/textshow/PBGlyph.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDAcroForm.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDAnnot.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDExtGState.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDHalftone.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDOutputIntent.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDPage.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/colors/PBoxPDDeviceN.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/colors/PBoxPDSeparation.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDCIDFont.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDTrueTypeFont.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDType0Font.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDType1Font.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDInlineImage.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDXImage.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/cos/PBCosFileSpecificationTest.java
model-implementation/src/test/java/org/verapdf/model/impl/pb/pd/PBoxPDOutputIntentTest.java
validation-logic/src/test/java/org/verapdf/validation/logic/TestPDAnnot.java

https://github.com/veraPDF/veraPDF-model/pull/66

New types implementation

---

model-implementation/src/main/java/org/verapdf/model/ModelLoader.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDXImage.java

Image mask is not image and don`t use color space

PT-268: Image Mask and ColorSpace

---

metadata-fixer/src/main/java/org/verapdf/metadata/fixer/impl/fixer/MetadataFixerEnum.java

Add 'transient' for enum field

Sonar fix for metadata fixer enum

---

core/src/main/java/org/verapdf/pdfa/validators/BaseValidator.java
gui/src/main/java/org/verapdf/cli/VeraPdfCli.java
gui/src/main/java/org/verapdf/cli/commands/VeraCliArgParser.java
gui/src/main/java/org/verapdf/gui/ValidateWorker.java
gui/src/main/java/org/verapdf/report/FeaturesReport.java

Added new CLI options:
- features reporting from CLI;
- MachineReadableReport selectable from CLI; and
- fixed validator initialisation bug.

New CLI options

---

gui/src/main/java/org/verapdf/cli/VeraPdfCliProcessor.java
gui/src/test/java/org/verapdf/cli/VeraPdfCliProcessorTest.java
gui/src/test/java/org/verapdf/cli/commands/VerCliFlavourTest.java
gui/src/test/java/org/verapdf/cli/commands/VeraCliArgParserTest.java
gui/src/test/java/org/verapdf/cli/commands/VeraCliGetPathsTest.java
gui/src/test/java/org/verapdf/cli/commands/VeraCliProfileOptionTest.java

- added tests for loading profile using -p / -- profile switch; and
- tidied exisiting CLI tests.

Fixed CLI Validation Profile loading

---

core/src/main/java/org/verapdf/pdfa/PDFAValidator.java
gui/src/main/java/org/verapdf/cli/VeraPdfCli.java
gui/src/main/java/org/verapdf/cli/VeraPdfCliProcessor.java
gui/src/main/java/org/verapdf/gui/CheckerPanel.java
gui/src/test/java/org/verapdf/cli/VeraPdfCliProcessorProfileTest.java
gui/src/test/java/org/verapdf/cli/VeraPdfCliProcessorTest.java
gui/src/test/resources/org/verapdf/profiles/PDFA-1A.xml
gui/src/test/resources/org/verapdf/profiles/PDFA-1B.xml
gui/src/test/resources/org/verapdf/profiles/PDFA-2B.xml
gui/src/test/resources/org/verapdf/profiles/PDFA-3B.xml
legacy-types/src/main/java/org/verapdf/validation/profile/parser/LegacyProfileConverter.java
legacy-types/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileParser.java
legacy-types/src/test/java/org/verapdf/validation/profile/parser/ValidationProfileParserTest.java
verapdf-qa/src/main/java/org/verapdf/pdfa/qa/GitHubBackedProfileDirectory.java
verapdf-qa/src/main/java/org/verapdf/pdfa/qa/RuleDirectory.java

- better tests for profile loading; and
- improvements to legacy profile convertor.

Fixes loading of CLI profiles

---

LICENSE-HEADERS.md
RELEASE.md

Added new documentation files:
- RELEASE.md contains instructions for versioning a new release using Maven; and
- LICENSE-HEADERS.md contains instructions for adding MPL and GPL license headers using Maven and create zip and compressed tarball archives using Git.

Enhanced build documentation.

---

core/src/main/java/org/verapdf/pdfa/results/ValidationResultImpl.java
core/src/main/java/org/verapdf/pdfa/results/ValidationResults.java
core/src/main/java/org/verapdf/pdfa/validation/Profiles.java
core/src/main/java/org/verapdf/pdfa/validation/ValidationProfileImpl.java
core/src/main/resources/org/verapdf/pdfa/results/validationResult.xsd
core/src/main/resources/org/verapdf/pdfa/validation/validationProfile.xsd
verapdf-qa/src/main/java/org/verapdf/pdfa/qa/GitHubBackedProfileDirectory.java

- added code to generated ValidationProfile and ValidationResult XSD schema; and
- committed generated schema to core/src/main/resources.

Profile conversion and schema

---

.travis.yml
gui/src/main/java/org/verapdf/cli/VeraPdfCliProcessor.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDMetadata.java
model-implementation/src/main/java/org/verapdf/model/tools/XMPChecker.java
pom.xml
verapdf-qa/src/main/java/org/verapdf/pdfa/qa/GitHubBackedProfileDirectory.java

Original pull request from @fthomas #439 was made against master, now merged against upstream integration with pending changes for travis, see #453.

Add space between file path and text

---

gui/src/main/java/org/verapdf/report/MachineReadableReport.java
gui/src/main/java/org/verapdf/report/ValidationReport.java

It's required only for batch processing so it should be implemented together.

Revert "Added method to obtain a result line."

---

installer/src/main/resources/org/verapdf/scripts/verapdf-install.bat

Closes veraPDF/veraPDF-library#398

Fixed installer script.

---

gui/src/main/java/org/verapdf/cli/VeraPdfCliProcessor.java
gui/src/main/java/org/verapdf/gui/tools/GUIConstants.java

Closes veraPDF/veraPDF-library#444

Fixed error message.

---

gui/src/main/java/org/verapdf/cli/commands/VeraCliArgParser.java
legacy-types/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileParser.java
model-implementation/src/main/java/org/verapdf/model/impl/axl/AXLXMPPackage.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/cos/PBCosDocument.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDAnnot.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDDocument.java
model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/images/PBoxPDXObject.java
verapdf-qa/src/main/java/org/verapdf/pdfa/qa/RuleDirectory.java

This pull request is focused on resolving occurrences of Sonar rule "squid:HiddenFieldCheck - Local variables should not shadow class fields". You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:HiddenFieldCheck
Please let me know if you have any questions.
Sameer Misger

Fixing squid:squid:HiddenFieldCheck --  Local variables should not shadow class fields

---

parent/pom.xml

Fixed developers information in parent pom

---

parent/pom.xml
pom.xml

- new parent POM manages build not dependencies; and
- dependency management added to library POM.

Fix - parent POM dependency management

---

.travis.yml
core/src/main/java/org/verapdf/core/ModelParsingException.java
core/src/main/java/org/verapdf/pdfa/PDFAValidator.java
core/src/main/java/org/verapdf/pdfa/ValidationModelParser.java
core/src/main/java/org/verapdf/pdfa/validators/BaseValidator.java

- specific Exception type for model parsing to facilitate non-PDF detection by caller
- closes #555

Added model parsing exception type.

---

.travis.yml
codecov.yml
parent/pom.xml
pom.xml

- updated parent POM and added jacoco for codecov;
- added codecov.yml for codecov integration;
- added Slack notification for Travis build; and
- added codecov call to Travis build.

FEAT - Codecov integration

---

.travis.yml
pom.xml

- added Jacoco to main POM file.

FIX - Codecov

---

README.md
RELEASENOTES.md
core/pom.xml
pom.xml

- bumped minor -> 0.18 for release;
- updated model dependency;
- added 0.18 RELEASENOTES.md; and
- fixed build badges in README.md.

REL - Release 0.18

---

core/pom.xml
pom.xml

- bumped minor to 0.19 for development; and
- updated model dependency for development.

REL - Development release 0.19

---

RELEASENOTES.md
core/pom.xml
pom.xml

- bumped minor -> 0.20 for release;
- updated RELEASENOTES.md; and

REL - Release 0.20

---

RELEASENOTES.md

FIX - Release notes for 0.20

---

core/pom.xml
pom.xml

- bumped minor -> 0.21 for development; and

DEV - Development version 0.21

---

RELEASENOTES.md

Added draft notes for 0.22 release

Draft 0.22 notes

---

core/pom.xml
pom.xml

- bumped minor -> 0.22 for release; and

REL - Release 0.22:

---

core/pom.xml
pom.xml

- bumped minor -> 0.23 for development; and

DEV - Development version 0.23 :

---

core/pom.xml
core/src/main/java/org/verapdf/features/tools/ErrorsHelper.java
core/src/main/java/org/verapdf/model/impl/axl/AXLPDFAIdentification.java
core/src/main/java/org/verapdf/model/tools/xmp/validators/DateTypeValidator.java
core/src/main/java/org/verapdf/model/tools/xmp/validators/URITypeValidator.java
core/src/main/java/org/verapdf/model/tools/xmp/validators/URLTypeValidator.java
core/src/main/java/org/verapdf/model/tools/xmp/validators/XPathTypeValidator.java
core/src/main/java/org/verapdf/pdfa/PDFParser.java

- removed log4j dependency from POM;
- replaced all instances of log4j with Java Logger; and
- improved some logging messages.

Feat - Remove log4j

---

core/src/main/java/org/verapdf/features/config/FeaturesConfig.java
core/src/main/java/org/verapdf/metadata/fixer/entity/PDFDocument.java
core/src/main/java/org/verapdf/metadata/fixer/utils/ProcessedObjectsInspector.java
core/src/main/java/org/verapdf/metadata/fixer/utils/ValidationStatus.java
core/src/main/java/org/verapdf/model/impl/axl/AXLXMPMMHistoryProperty.java
core/src/main/java/org/verapdf/model/impl/axl/AXLXMPPackage.java
core/src/main/java/org/verapdf/pdfa/PDFParser.java
core/src/test/java/org/verapdf/model/impl/axl/XMPExtensionSchemaTest.java
core/src/test/java/org/verapdf/model/impl/axl/XMPMMHistoryTest.java

- removed un-thrown exception declarations;
- removed unused imports; and
- fixed boxing and unboxing warnings.

Fix compiler warnings

---

RELEASENOTES.md
core/pom.xml
pom.xml

- bumped minor -> 0.24 for release;
- updated model dependency; and
- add v0.24 release notes.

Release 0.24

---

core/pom.xml
pom.xml

- bumped minor -> 0.25 for development; and

DEV - Development version 0.25

---

core/src/main/java/org/verapdf/component/Component.java
core/src/main/java/org/verapdf/component/ComponentDetails.java
core/src/main/java/org/verapdf/component/ComponentDetailsImpl.java
core/src/main/java/org/verapdf/component/Components.java

- new interfaces enforcing component details;
- reference implementation of component details; and
- convenience class for instantiation.

FEAT - Component details

---

core/src/main/java/org/verapdf/features/FeatureFactory.java
core/src/main/java/org/verapdf/processor/ProcessorConfig.java

- FeaturesConfig factory now serialises to stream instead of returning an unused string.

FIX - Features Config

---

core/src/main/java/org/verapdf/ReleaseDetails.java
core/src/main/java/org/verapdf/component/AuditDurationImpl.java
core/src/main/java/org/verapdf/component/Components.java
core/src/main/java/org/verapdf/pdfa/results/ValidationResult.java
core/src/main/java/org/verapdf/pdfa/results/ValidationResultImpl.java
core/src/main/java/org/verapdf/pdfa/results/ValidationResults.java
core/src/main/java/org/verapdf/pdfa/validation/validators/BaseValidator.java
core/src/main/java/org/verapdf/processor/MrrHandler.java
core/src/test/java/org/verapdf/pdfa/results/ValidationResultTest.java

- removed rights statement from standard release details;
- added static rights method for rights info;
- tidied compiler warnings;
- added ProfileDetails to ValidationResult for reporting;
- updated ValidationResult unit tests; and
- added profile name to MRR report.

FIX - MRR Details

---

core/src/main/java/org/verapdf/processor/RawResultHandler.java

- cleaned up fragments and wrapped in a rawResult element.

FIX - CLI raw report

---

core/src/main/java/org/verapdf/core/utils/FileOutputMappers.java
core/src/main/java/org/verapdf/core/utils/SingleOutputDirMapper.java
core/src/main/java/org/verapdf/core/utils/VersioningMapper.java
core/src/main/java/org/verapdf/processor/MrrHandler.java
core/src/main/java/org/verapdf/processor/ProcessorConfigImpl.java
core/src/main/java/org/verapdf/processor/ProcessorFactory.java
core/src/main/java/org/verapdf/processor/ProcessorImpl.java
core/src/main/java/org/verapdf/processor/RawResultHandler.java

- fixed XML report structure;
- added flushes to writer;
- prefix now honoured;
- folder now used; and
- added versioning to files by default.

FIX - metadata fixer output and raw results

---

core/src/main/java/org/verapdf/processor/ProcessorImpl.java

- use default current folder when user choice is null or empty.

FIX - empty folder

---

core/src/main/java/org/verapdf/processor/ProcessorImpl.java

- reversed schoolboy logic error from previous fix.

FIX - Empty folder param

---

core/pom.xml
pom.xml

- bumped minor -> 0.27 for development; and
- updated model dependency

DEV - Development version 0.27

---

core/src/main/java/org/verapdf/policy/PolicyChecker.java

- added parameter to the policy transform.

FIX - Policy Transform Parameter

---

core/src/main/java/org/verapdf/policy/PolicyChecker.java
core/src/test/java/org/verapdf/policy/PolicyCheckerTests.java

- simplified tempfile handling in PolicyChecker tests; and
- fixed import warnings.

FIX - Policy Checker tests

---

core/src/main/java/org/verapdf/report/HTMLReport.java

- fixed my schoolby spelling error for XSL extenstion.

FIX - Multi-file HTML reporting

---

core/src/main/resources/org/verapdf/policy/MergeMrrPolicy.xsl

- ammended XSLT that merges MRR and policy report;
- passed and failed checks now inserted into appropriate jobs; and
- wrapped in a per-job summary.

FIX - Merge Policy Elements

---

core/src/main/resources/org/verapdf/report/DetailedHtmlReport.xsl

Now displaying proper names for features

Updated features report

---

core/src/main/java/org/verapdf/processor/TaskResultImpl.java

- handling null exception case for message.
Closes #646

FIX - Null Task Exception

---

core/src/main/resources/org/verapdf/policy/MergeMrrPolicy.xsl

- amended merge stylesheet to work with single result.

FIX - Single File Policy Merge

---

core/src/main/resources/org/verapdf/report/DetailedHtmlReport.xsl

- added policy summary to the top of the report; and
- added policy section to the report details.

FEAT - Detailed Policy Report

---

core/src/main/resources/org/verapdf/report/DetailedHtmlReport.xsl

- fixed faulty xpath for policy status; and
- corrected accidental change to validation report.

FIX - Detailed Report

---

core/src/main/resources/org/verapdf/report/DetailedHtmlReport.xsl
core/src/main/resources/org/verapdf/report/SummaryHtmlReport.xsl

- corrected xPath for failed policy count query; and
- fixed compliance message colour in detailed report.

FIX - HTML Report fixes

---

RELEASENOTES.md
core/pom.xml
pom.xml

- bumped minor -> 0.28 for release;
- updated model dependency; and
- added release 0.28 release notes.

REL - Release 0.28

---

core/pom.xml
pom.xml

- bumped minor -> 0.29 for development; and

DEV - Development version 0.29

---

core/src/main/java/org/verapdf/processor/TaskResultImpl.java

Fixed equals and hashcode methods for TaskResultImpl class

---

core/src/main/java/org/verapdf/core/XmlSerialiser.java
core/src/main/java/org/verapdf/core/utils/FileOutputMappers.java
core/src/main/java/org/verapdf/pdfa/PDFAValidator.java
core/src/main/resources/org/verapdf/policy/schematron/pipeline/iso_schematron_message.xsl
core/src/main/resources/org/verapdf/policy/schematron/pipeline/iso_schematron_skeleton_for_xslt1.xsl
core/src/main/resources/org/verapdf/policy/schematron/pipeline/iso_svrl_for_xslt1.xsl

patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer )

spelling fixes

---

core/pom.xml
core/src/main/java/org/verapdf/component/AuditDuration.java
core/src/main/java/org/verapdf/component/ComponentDetails.java
core/src/main/java/org/verapdf/component/Components.java
core/src/main/java/org/verapdf/pdfa/Foundries.java
core/src/main/java/org/verapdf/pdfa/MetadataFixer.java
core/src/main/java/org/verapdf/pdfa/PDFAParser.java
core/src/main/java/org/verapdf/pdfa/VeraFoundryProvider.java
core/src/main/java/org/verapdf/pdfa/VeraPDFFoundry.java
core/src/main/java/org/verapdf/pdfa/validation/validators/ValidatorConfig.java
core/src/main/java/org/verapdf/pdfa/validation/validators/ValidatorFactory.java
core/src/main/java/org/verapdf/policy/PolicyChecker.java
core/src/main/java/org/verapdf/processor/AbstractBatchHandler.java
core/src/main/java/org/verapdf/processor/BatchFileProcessor.java
core/src/main/java/org/verapdf/processor/BatchProcessingHandler.java
core/src/main/java/org/verapdf/processor/BatchProcessor.java
core/src/main/java/org/verapdf/processor/ItemProcessor.java
core/src/main/java/org/verapdf/processor/Processor.java
core/src/main/java/org/verapdf/processor/ProcessorConfig.java
core/src/main/java/org/verapdf/processor/TaskResult.java
core/src/main/java/org/verapdf/processor/reports/BatchSummary.java
core/src/main/java/org/verapdf/processor/reports/Check.java
core/src/main/java/org/verapdf/processor/reports/ItemDetails.java
core/src/main/java/org/verapdf/processor/reports/MetadataFixerReport.java

- updated JavaDoc for API methods;
- amended Maven scope for xml-unit; and
- suppressed externalised string warnings where appropriate;

FEAT - JavaDoc update

---

RELEASENOTES.md
core/pom.xml
pom.xml

- bumped minor -> 1.3 for development; and

DEV - Development version 1.3

---

core/src/main/java/org/verapdf/processor/SingleLineResultHandler.java

- CLI now outputs passed check details if -v and --success set.
Closes #591

FEAT - CLI text mode successful test logging

---

core/src/main/java/org/verapdf/pdfa/results/ValidationResults.java
core/src/main/java/org/verapdf/processor/reports/Reports.java
core/src/main/java/org/verapdf/processor/reports/ValidationReport.java
core/src/test/java/org/verapdf/pdfa/results/LocationTest.java
core/src/test/java/org/verapdf/pdfa/results/TestAssertionTest.java
core/src/test/java/org/verapdf/pdfa/results/ValidationResultTest.java

- added deserialise from XML string methods for `ValidationResult` and ValidationReport;
- added tests for result method; and
- tidied some externalised String warnings.

FIX - XML Report & Result Deserialisation

---

core/src/main/java/org/verapdf/component/AuditDuration.java
core/src/main/java/org/verapdf/component/AuditDurationImpl.java
core/src/test/java/org/verapdf/component/AuditDurationImplTest.java

Merged from PR #687, many thanks to @rillig
* removed redundant "public" modifier
* replaced equals/hashCode with shorter code
* fixed message in IllegalArgumentException
* made getStringDuration code shorter
* added unit test

Cleaned up code in AuditDuration

---

core/src/main/java/org/verapdf/core/utils/FileUtils.java
core/src/main/java/org/verapdf/policy/PolicyChecker.java
core/src/main/java/org/verapdf/policy/SchematronPipeline.java
core/src/test/java/org/verapdf/core/utils/FileUtilsTest.java

- FileUtils class for file extension handling;
- factored out some funtionality from PolicyChecker; and
- tidied basic warnings.

FEAT - Schema Utilities

---

core/src/main/java/org/verapdf/core/utils/FileUtils.java
core/src/main/java/org/verapdf/features/objects/FontFeaturesObject.java
core/src/test/java/org/verapdf/core/utils/FileUtilsTest.java

- fixed mistake in extension test method;
- added tests to prevent extension test regresssion; and
- cleaned up potential null pointer access in FontFeaturesObject.

FIX - File Utilities

---

.travis.yml
README.md
RELEASENOTES.md
core/pom.xml
parent/pom.xml
pom.xml

- bumped minor to 1.4 for release;
- got ready for Maven central publishing;
- added test coverage publication;
- updated README build instructions; and
- updated README badges.

REL - Release v1.4

---

core/pom.xml
pom.xml

- bumped minor -> 1.5 for development.

DEV - Development v1.5

---

core/src/main/java/org/verapdf/SemanticVersionNumber.java
core/src/main/java/org/verapdf/VersionNumberImpl.java
core/src/test/java/org/verapdf/SemanticVersionTest.java

- basic interface for semantic version numbers;
- implementation with comparable; and
- unit tests for most cases.

FEAT - Version comparison

---

core/src/main/java/org/verapdf/SemanticVersionNumber.java
core/src/main/java/org/verapdf/VersionNumberImpl.java
core/src/test/java/org/verapdf/SemanticVersionTest.java

- removed explicit handling of `-PDFBOX`, `-SNAPSHOT` postfixes;
- removed explicit handling of `v` prefix;
- implemented naive handling of pre-release and build metadata; and
- removed version tests.

FEAT - Semantic versioning class

---

core/pom.xml
pom.xml

- bumped minor -> 1.6 for release;

REL - Release v1.6

---

core/pom.xml
pom.xml

- bumped minor -> 1.7 for development; and

REL - Development version v1.7

---

RELEASENOTES.md
core/pom.xml
pom.xml

- bumped minor -> 1.8 for release;
- updated model dependency; and
- updated release notes.

REL - Release v1.8

---

core/pom.xml
pom.xml

- bumped minor -> 1.9 for development; and

REL - Development version v1.9

---

core/src/main/java/org/verapdf/pdfa/results/ValidationResult.java
core/src/main/java/org/verapdf/pdfa/results/ValidationResultImpl.java
core/src/main/java/org/verapdf/pdfa/results/ValidationResults.java
core/src/main/java/org/verapdf/pdfa/validation/validators/BaseValidator.java
core/src/main/java/org/verapdf/processor/reports/RuleSummaryImpl.java
core/src/main/java/org/verapdf/processor/reports/ValidationDetailsImpl.java
core/src/test/java/org/verapdf/pdfa/results/ValidationResultTest.java

Fixed reporting logic with custom profiles

---

parent/pom.xml

- updated parent POM version to 1.12;
- updated various plugins to latest versions;
- added missing plugin management entries; and
- removed defunct plugins and profiles.

DEV - Updated parent POM.XML

---

core/src/main/java/org/verapdf/processor/FeaturesPluginsLoader.java

- improved warnings when config loading fails.
contributes to #949

FIX - Plugins config loader

---

core/pom.xml
parent/pom.xml
pom.xml
xmp-core/pom.xml

- bumped version -> 1.17; and
- updated dependency ranges.

DEV: v1.17

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-1.xml

Required: https://github.com/veraPDF/veraPDF-validation/pull/322, https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/215

PDF/UA validation. Fix PDF/UA profile

---

core/src/main/java/org/verapdf/component/AuditDuration.java
core/src/main/java/org/verapdf/model/impl/axl/AXLXMPLangAlt.java
core/src/main/java/org/verapdf/model/impl/axl/AXLXMPPackage.java
core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-1.xml
xmp-core/src/main/java/com/adobe/xmp/impl/VeraPDFXMPNode.java
xmp-core/src/main/java/com/adobe/xmp/impl/XMPNode.java

Required: https://github.com/veraPDF/veraPDF-model/pull/204

PDF/UA validation. Fix rule 7.2.33

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-1.xml

Required: https://github.com/veraPDF/veraPDF-model/pull/214

PDF-UA validation. Fix rule 7.18.6.2-2

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-1.xml

Required: https://github.com/veraPDF/veraPDF-model/pull/215

PDF-UA validation. Fix rules 7.18.6.2-1, 7.18.6.2-2

---

core/pom.xml
parent/pom.xml
pom.xml
xmp-core/pom.xml

bumped version -> 1.19
updated dependency ranges

DEV: v1.19

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4E.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4F.xml

PDF/A-4 validation. Add rules 6.7.3-5, 6.9-4.

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4E.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4F.xml

PDF/A-4 validation. Add rule 6.7.2.1-5

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2A.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2B.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2U.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3A.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3B.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3U.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4E.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4F.xml

Add rules 6.2.4.2-3, 6.2.4.3-2, 6.2.4.3-3, 6.7.2.1-5
Fix rules 6.3.3-1, 6.6.1-1, 6.7.3-1
Required: https://github.com/veraPDF/veraPDF-validation/pull/376, https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/243

Fix PDF/A-4 profile.

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2A.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2B.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2U.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3A.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3B.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3U.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4E.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4F.xml

PDF/A validation. Fix rules 6.2.4.4-2, 6.2.7.3-2 - 6.2.7.3-4

---

core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2A.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2B.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2U.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3A.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3B.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3U.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4E.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4F.xml
core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-1.xml

PDF/UA validation. Fix rule 7.21.3.2-1

PDF/A validation. Fix rules 6.2.11.3-2 and 6.2.10.3.2-1

---

RELEASENOTES.md
core/pom.xml
parent/pom.xml
pom.xml
xmp-core/pom.xml

- bumped version -> 1.21
- updated dependency ranges

DEV: v1.21

---

.github/workflows/test-pr.yml

- Java 8, 11 and 16 builds;
- code coverage on Codecov; and
- static QA on Codacy.

MAINT: Added GitHub action for PRs.

---

core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

- bumped minor version to 1.22
- updated Maven dependency

REL - Release v1.22

---

core/pom.xml
parent/pom.xml
pom.xml
xmp-core/pom.xml

- bumped version -> 1.23
- updated parent version

DEV: v1.23

---

core/src/main/java/org/verapdf/processor/BatchFileProcessor.java
core/src/main/java/org/verapdf/processor/FeaturesPluginsLoader.java

Replace / to \ in archive files path

Add NoClassDefFoundError catching to plugins loader

---

README.md
core/src/main/java/org/verapdf/metadata/fixer/utils/MetadataFixerConstants.java

Update date regex.

---

README.md
core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

- bumped minor version to 1.24
- updated Maven dependency

REL - Release v1.24

---

.github/workflows/test-pr.yml
README.md
core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

- bumped minor version to 1.24
- updated Maven dependency

REL - Release v1.24 (jakarta)

---

README.md
core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

DEV: v1.25

---

core/src/main/java/org/verapdf/metadata/fixer/utils/parser/XMLProcessedObjectsParser.java
core/src/main/java/org/verapdf/pdfa/results/TestAssertion.java
core/src/main/resources/org/verapdf/metadata/fixer/processed-objects.properties
core/src/main/resources/org/verapdf/metadata/fixer/processedObjectsPDFUA_2.xml
core/src/main/resources/org/verapdf/report/DetailedHtmlReport.xsl
core/src/test/java/org/verapdf/ReleaseDetailsTest.java
core/src/test/java/org/verapdf/pdfa/results/TestAssertionTest.java
core/src/test/java/org/verapdf/pdfa/validation/profiles/ProfileDirectoryImplTest.java
core/src/test/java/org/verapdf/pdfa/validation/profiles/ReferenceImplTest.java
core/src/test/java/org/verapdf/pdfa/validation/profiles/RuleIdImplTest.java
core/src/test/java/org/verapdf/pdfa/validation/profiles/ValidationProfileImplTest.java
core/src/test/java/org/verapdf/pdfa/validation/profiles/VariableImplTest.java
xmp-core/src/main/java/org/verapdf/xmp/impl/VeraPDFMeta.java

PDF/UA-2. Support links to profiles wiki

---

README.md
RELEASENOTES.md
core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

- bumped minor version to 1.26
- updated parent version to 1.26.2

REL - v1.26

---

README.md
RELEASENOTES.md
core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

- bumped minor version to 1.26
- updated parent version to 1.26.2

REL - v1.26 (jakarta)

---

core/src/main/java/org/verapdf/component/ComponentDetailsImpl.java
core/src/main/java/org/verapdf/features/FeatureObjectType.java
core/src/main/java/org/verapdf/features/objects/AnnotationFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/ColorSpaceFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/ExtGStateFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/FormXObjectFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/ICCProfileFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/InfoDictFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/InteractiveFormFieldFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/LowLvlInfoFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/OutlinesFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/OutputIntentFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/PageFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/PostScriptFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/PropertiesDictFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/ShadingFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/ShadingPatternFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/SignatureFeaturesObject.java
core/src/main/java/org/verapdf/features/objects/TilingPatternFeaturesObject.java
core/src/main/java/org/verapdf/metadata/fixer/FixerConfigImpl.java
core/src/main/java/org/verapdf/metadata/fixer/entity/Metadata.java
core/src/main/java/org/verapdf/metadata/fixer/entity/PDFDocument.java
core/src/main/java/org/verapdf/pdfa/VeraPDFFoundry.java
core/src/main/java/org/verapdf/processor/ProcessorResultImpl.java
core/src/main/java/org/verapdf/processor/reports/BatchSummaryImpl.java
core/src/main/java/org/verapdf/processor/reports/CheckImpl.java
core/src/main/java/org/verapdf/processor/reports/FixerReportImpl.java
core/src/main/java/org/verapdf/processor/reports/RuleSummaryImpl.java
core/src/main/java/org/verapdf/processor/reports/ValidationDetailsImpl.java
core/src/main/java/org/verapdf/processor/reports/ValidationReportImpl.java

https://github.com/veraPDF/veraPDF-library/issues/683

Remove redundant comments

---

README.md
core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

- bumped minor version to 1.28

REL - v1.28

---

README.md
core/pom.xml
pom.xml
xmp-core-coverage/pom.xml
xmp-core/pom.xml

- bumped minor version to 1.28

REL - v1.28 (jakarta)
