veraPDF/veraPDF-library

validationlogic/src/main/java/org/verapdf/validation/logic/Validator.java, validationlogic/src/main/java/org/verapdf/validation/report/XMLValidationReport.java, validationlogic/src/main/java/org/verapdf/validation/report/model/CheckLocation.java, validationlogic/src/test/java/org/verapdf/validation/logic/TestCosDict.java, validationlogic/src/test/java/org/verapdf/validation/logic/ValidationLogicTest.java, validationprofileparser/src/main/java/org/verapdf/validation/profile/parser/ValidationProfileParser.java
1) Previous context was list of link types separated by " - ". Now it's list of link names with indices (for each link) and separated by "/". 
2) Previously all objects checked just 1 time (without looking at their context). Now it checking any object with unique path to it (by id). With preventing loops.
3) Added javadoc for all exceptions.
=> Validationlogic. Changed context view in report and added JavaDoc for exceptions.

.travis.yml, model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDMetadata.java, model-implementation/src/main/java/org/verapdf/model/tools/XMPChecker.java, pom.xml, verapdf-qa/src/main/java/org/verapdf/pdfa/qa/GitHubBackedProfileDirectory.java
Fixes to get Travis build going:
- profiles test now uses new profiles;
- moved logging of XMP exceptions to DEBUG level;
- moved building of QA tests to Maven clone-test-resources profile; and
- disabled build of QA tests on Travis.
=> Fix Travis build

core/src/main/java/org/verapdf/pdfa/results/ValidationResult.java, core/src/main/java/org/verapdf/pdfa/results/package-info.java, core/src/main/java/org/verapdf/pdfa/validation/package-info.java, core/src/main/resources/org/verapdf/pdfa/validation/PDFA-1A.xml, core/src/main/resources/org/verapdf/pdfa/validation/PDFA-1B.xml, core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2B.xml, core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3B.xml, gui/src/main/java/org/verapdf/cli/VeraPdfCliProcessor.java, gui/src/main/java/org/verapdf/report/CliReport.java, gui/src/main/java/org/verapdf/report/package-info.java
Updates and minor fixes:
- up to date validation profiles now in the core resources;
- namespace consistency across entities (may need reviewing);
- all logging output to stderr, fixes #430; and
- single XML document for CLI output, fixes #411.
=> Single XML doc, update to core profiles and bug fixes

gui/src/main/java/org/verapdf/cli/VeraPdfCli.java
STDIN processing no longer triggered if any of the following commands are present and the file list is empty:
verapdf --version
verapdf -h
verapdf --help
verapdf -l
verapdf --list
=> Fixed greedy processing of stdin.

gui/src/main/java/org/verapdf/gui/CheckerPanel.java, gui/src/main/java/org/verapdf/report/MetadataFixesReport.java, metadata-fixer/src/main/java/org/verapdf/metadata/fixer/utils/parser/XMLProcessedObjectsParser.java, model-implementation/src/main/java/org/verapdf/model/tools/xmp/SchemasDefinitionCreator.java, model-implementation/src/main/java/org/verapdf/model/tools/xmp/ValidatorsContainerCreator.java
This pull request is focused on resolving occurrences of Sonar rule "squid:SwitchLastCaseIsDefaultCheck - "switch" statements should end with a "default" clause". You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:SwitchLastCaseIsDefaultCheck
Please let me know if you have any questions.
Sameer Misger
=> Fixing squid:SwitchLastCaseIsDefaultCheck - "switch" statements should end with a "default" clause

core/src/main/java/org/verapdf/pdfa/validators/BaseValidator.java, feature-report/src/main/java/org/verapdf/features/FeaturesPluginsLoader.java, gui/src/main/java/org/verapdf/report/ValidationReport.java, model-implementation/src/main/java/org/verapdf/model/impl/axl/AXLExtensionSchemasContainer.java, model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/PBoxPDStructElem.java, model-implementation/src/main/java/org/verapdf/model/impl/pb/pd/font/PBoxPDCIDFont.java, model-implementation/src/main/java/org/verapdf/model/tools/TaggedPDFHelper.java, model-implementation/src/main/java/org/verapdf/model/tools/xmp/validators/ArrayTypeValidator.java
This pull request is focused on resolving occurrences of Sonar rule " UselessParenthesesCheck -     Useless parentheses around expressions should be removed to prevent any misunderstanding". You can find more information about the issues here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions.
Sameer Misger
=> Fixing squid:UselessParenthesesCheck-Useless parentheses around expressions should be removed to prevent any misunderstanding

parent/pom.xml
- Added JavaDoc exclusions so verapdf-pdfbox-validation builds OK.
- Added no-fail to JavaDoc generation just in case.
=> Exclusions + no-fail for JavaDoc back.

core/src/main/java/org/verapdf/ReleaseDetails.java
- added or later to Mozilla license text.
Fixes veraPDF/veraPDF-apps#60.
=> FIX - License text:

core/src/main/java/org/verapdf/ReleaseDetails.java, core/src/main/java/org/verapdf/core/JAXBCollection.java, core/src/main/java/org/verapdf/core/XmlSerialiser.java, core/src/main/java/org/verapdf/model/tools/xmp/validators/DateTypeValidator.java, core/src/main/java/org/verapdf/pdfa/results/ValidationResultImpl.java, core/src/main/java/org/verapdf/pdfa/results/ValidationResults.java, core/src/main/java/org/verapdf/processor/BatchSummary.java, core/src/main/java/org/verapdf/processor/BatchSummaryImpl.java, core/src/main/java/org/verapdf/processor/ItemProcessor.java, core/src/main/java/org/verapdf/processor/Processor.java, core/src/main/java/org/verapdf/processor/ProcessorFactory.java, core/src/main/java/org/verapdf/processor/ProcessorImpl.java, core/src/main/java/org/verapdf/processor/StreamingProcessor.java, core/src/main/java/org/verapdf/processor/StreamingProcessorImpl.java, core/src/test/java/org/verapdf/pdfa/results/ValidationResultTest.java
- added convenience method to ReleaseDetails to get the full details Collection;
- renamed existing processor interface to ItemProcessor;
- tweaked agressive exception warning for bad dates;
- tidied code formatting;
- xml serialiser now use primitives;
- added generic handler for JAXB types; and
- added new StreamingProcessor interface and implementation.
=> REFACT - Streaming Processor

core/src/main/java/org/verapdf/processor/TaskResultImpl.java
Closes https://github.com/veraPDF/veraPDF-apps/issues/115.
=> Fixed null in getType() in TaskResultImpl.

README.md
- removed space in `java - jar` command;
- replaced "definitive" with "industry supported"; and
- fixed heading issues.
=> DOC - README.md typos

core/pom.xml, core/src/main/java/org/verapdf/ReleaseDetails.java, core/src/main/java/org/verapdf/core/XmlSerialiser.java, core/src/main/java/org/verapdf/pdfa/results/ValidationResults.java, core/src/main/java/org/verapdf/processor/AbstractBatchHandler.java, core/src/main/java/org/verapdf/processor/AbstractXmlHandler.java, core/src/main/java/org/verapdf/processor/MrrHandler.java, core/src/main/java/org/verapdf/processor/ProcessorFactory.java, core/src/main/java/org/verapdf/processor/RawResultHandler.java, core/src/main/java/org/verapdf/processor/reports/ValidationReportImpl.java
- replaced `XMLStreamWriter` with `IndentingXMLStreamWriter` from `stax-utils`;
- purged some externalised String warnings with `//$NON-NLS-1$`;
- fixed unparameterised Class warning in `XMLSerialiser`;
- removed old indent hack from `BatchFileProcessor`;
- factored all Strings into single constants; and
- refactored element serialisation and exception handling.
Closes #119
=> FEAT - Pretty Print XML Reports

core/src/main/java/org/verapdf/component/AuditDuration.java, core/src/main/java/org/verapdf/component/AuditDurationImpl.java, core/src/test/java/org/verapdf/component/AuditDurationImplTest.java
* removed redundant Javadoc
* removed redundant "public" modifier
* replaced equals/hashCode with shorter code
* fixed message in IllegalArgumentException
* made getStringDuration code shorter
* added unit test
This re-adds what some consider magic numbers to the code. On second
thought, the numbers 60 and 1000 are not magic at all when used in time
calculations, therefore there is no need to represent them as named
constants.
=> Cleaned up code in AuditDuration

LICENSE-HEADERS.md, README.md, RELEASE.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

core/src/main/java/org/verapdf/component/AuditDurationImpl.java, core/src/main/java/org/verapdf/features/objects/Feature.java, core/src/main/java/org/verapdf/features/objects/FeaturesObject.java, core/src/main/java/org/verapdf/model/tools/xmp/validators/URITypeValidator.java, core/src/main/java/org/verapdf/processor/MrrHandler.java, core/src/main/java/org/verapdf/processor/SingleLineResultHandler.java, core/src/main/java/org/verapdf/processor/plugins/PluginConfig.java, core/src/main/java/org/verapdf/report/FeaturesNode.java, core/src/main/java/org/verapdf/report/FeaturesReport.java, core/src/test/java/org/verapdf/component/AuditDurationImplTest.java
Closes #689 
- jobs now report full duration details, not just string representation;
- AuditDurationImpl sumDuration method now returns an AuditDuration;
- more unit tests for AuditDuration;
- tidied compiler warnings;
- suppressed externalised string warnings; and
- removed unused code.
=> FIX - Audit Duration Reporting

core/src/main/java/org/verapdf/processor/AbstractBatchHandler.java, core/src/main/java/org/verapdf/processor/AbstractBatchProcessor.java, core/src/main/java/org/verapdf/processor/ProcessorFactory.java, core/src/main/java/org/verapdf/processor/ProcessorResult.java, core/src/main/java/org/verapdf/processor/ProcessorResultImpl.java, core/src/main/java/org/verapdf/processor/reports/AbstractBatchJobSummary.java, core/src/main/java/org/verapdf/processor/reports/BatchJobSummary.java, core/src/main/java/org/verapdf/processor/reports/BatchSummary.java, core/src/main/java/org/verapdf/processor/reports/BatchSummaryImpl.java, core/src/main/java/org/verapdf/processor/reports/FeaturesBatchSummary.java, core/src/main/java/org/verapdf/processor/reports/MetadataRepairBatchSummary.java, core/src/main/java/org/verapdf/processor/reports/Reports.java, core/src/main/java/org/verapdf/processor/reports/Summarisers.java, core/src/main/java/org/verapdf/processor/reports/ValidationBatchSummary.java, core/src/main/java/org/verapdf/processor/reports/ValidationBatchSummaryImpl.java, core/src/main/java/org/verapdf/report/HTMLReport.java, core/src/main/resources/org/verapdf/policy/MergeMrrPolicy.xsl, core/src/main/resources/org/verapdf/report/DetailedHtmlReport.xsl, core/src/main/resources/org/verapdf/report/SummaryHtmlReport.xsl, core/src/test/java/org/verapdf/processor/reports/ValidationBatchSummaryTest.java
Closes #707, closes veraPDF/veraPDF-validation#159
- added summary types for validation, features and metadata repair;
- created convenience builders for summary types;
- parsing failures and encrypted PDFs now have dedicated fields;
- tests for ValidationBatchSummary;
- fixed changed paths in XSLT report templates;
- ensured that HTML report picks up gui app version details; and
- done away with reporting of policy check numbers.
=> FIX - XML Report Clarity

core/src/main/java/org/verapdf/component/AuditDurationImpl.java, core/src/test/java/org/verapdf/component/AuditDurationImplTest.java
More closely aligns with English convention (".") and ISO date-time standard 8601 ("," or ".").
=> Change millisecond separator to a standard decimal mark

README.md, RELEASENOTES.md, core/pom.xml, core/src/main/java/org/verapdf/metadata/fixer/utils/MetadataFixerConstants.java, core/src/main/java/org/verapdf/metadata/fixer/utils/parser/XMLProcessedObjectsParser.java, core/src/main/resources/org/verapdf/metadata/fixer/processed-objects.properties, pom.xml
- fixed metadata fixed for Java 9;
- bumped minor -> 1.10 for release;
- updated model dependency; and
- added issue and PR badges to README.md.
=> REL - Release v1.10

core/pom.xml, parent/pom.xml, pom.xml
- bumped minor version -> 1.11 for development;
- updated model dependency to 1.11;
- updated parent pom version to 1.12.2 for Java 8;
- updated Mozilla Rhino dependency to 1.7.7.2; and
- updated Maven plugins and dependencies.
=>  REL - Development version v1.11

core/src/main/java/org/verapdf/model/impl/axl/AXLExtensionSchemaDefinition.java, core/src/main/java/org/verapdf/model/impl/axl/AXLExtensionSchemasContainer.java, core/src/main/java/org/verapdf/model/impl/axl/AXLXMPPackage.java, core/src/main/java/org/verapdf/model/tools/xmp/SchemasDefinitionCreator.java, core/src/main/java/org/verapdf/model/tools/xmp/ValidatorsContainer.java, core/src/main/java/org/verapdf/model/tools/xmp/ValidatorsContainerCreator.java
closes https://github.com/veraPDF/veraPDF-library/issues/916
=> fixed metadata extension logic

core/src/main/java/org/verapdf/pdfa/results/ValidationResult.java, core/src/main/java/org/verapdf/pdfa/results/ValidationResultImpl.java, core/src/main/java/org/verapdf/pdfa/results/ValidationResults.java, core/src/main/java/org/verapdf/pdfa/validation/validators/BaseValidator.java, core/src/main/java/org/verapdf/processor/reports/RuleSummary.java, core/src/main/java/org/verapdf/processor/reports/RuleSummaryImpl.java, core/src/main/java/org/verapdf/processor/reports/ValidationDetailsImpl.java, core/src/test/java/org/verapdf/pdfa/results/ValidationResultTest.java
Updated BaseValidator method processAssertionResult to avoid out of memory exception. Out of memory exception arose because of saving too many details after checking some rules.
Integration tests passed.
Closes  https://github.com/veraPDF/veraPDF-library/issues/905.
=> Fixed issue: #905.

pom.xml
Should ensure that the parent gets published with other Maven artifacts.
=> FIX: Include parent in reactor.

core/src/main/java/org/verapdf/pdfa/validation/validators/JavaScriptEvaluator.java
JavaScriptEvaluator.getTestEvalResult blocks threads while concurrent validation 
Thus I created issue #1408
This is the pull request to fix the issue.
=> Performance optimization for multi-threaded execution

.github/workflows/update-arlington-workflow.yml, .github/workflows/update-jakarta-workflow.yml, README.md, core/pom.xml, pom.xml, xmp-core-coverage/pom.xml, xmp-core/pom.xml
=> DEV: v1.27
